export const CATEGORY_OPTIONS = [
  "Tech",
  "Casa e decoração",
  "Pet",
  "Automóveis",
  "Beleza e saúde",
  "Eletrônicos",
  "Eletrodomésticos",
  "Bijoux",
  "Fitness",
  "Moda Masculina",
  "Moda Feminina",
  "Moda Infantil",
  "Bebe e Maternidade",
  "Brinquedos",
  "Cama, mesa e banho",
  "Games",
  "Produtos de Limpeza",
  "Alimentos",
];
